### ISSUE TITLE
Generic function causes parsing error

### ISSUE THREAD

**Issue by mariusschulz** [eslint/typescript-eslint-parser#420] opened 2017-12-21 10:47 UTC
**What version of TypeScript are you using?**
2.6.2

**What version of `typescript-eslint-parser` are you using?**
11.0.0

**What code were you trying to parse?**

_index.ts_ within a TypeScript project with JSX enabled:

```ts
const id = <T>(x: T) => x;
```

**What did you expect to happen?**
No parsing error.

**What happened?**
A parsing error:

```
Parsing error: JSX element 'T' has no corresponding closing tag
```

**Comment by mightyiam** [comment] 2017-12-21 11:28
Can't use the `<T>` syntax of type assertion with JSX, I think.

**Comment by mariusschulz** [comment] 2017-12-21 11:41
You're right, you can't use `<T>` for type assertions. However, in my example, I'm not using a type assertion — I'm just declaring a type parameter to make the function generic. TypeScript happily compiles the code.

**Comment by JamesHenry** [comment] 2017-12-21 11:50
Thanks, @mariusschulz!

The issue is not limited to type assertions, it applies to any ambiguous constructs. This is one such construct. TypeScript cannot compile this with jsx enabled, which as you said is the case here.

This, therefore, comes under https://github.com/eslint/typescript-eslint-parser/issues/399, so I am going to close this.

**Closed by JamesHenry** 2017-12-21 11:50 UTC
Labels: triage
