### ISSUE TITLE
getting `Cannot read property 'type' of undefined` on tsx file

### ISSUE THREAD

**Issue by evollu** [eslint/typescript-eslint-parser#172] opened 2017-02-24 20:09 UTC
**What version of TypeScript are you using?**
2.2.1

**What version of `typescript-eslint-parser` are you using?**
2.0.0

**What code were you trying to parse?**

```

class App extends React.PureComponent<void, void> {
  render () {
    return (
      <Provider store={store}>
        <View style={{ flex: 1 }}>
          <StatusBar barStyle='light-content' />
          <Navigator />
          <Loader />
          <AlertModal />
        </View>
      </Provider>
    );
  }
}

```

**What happened?**

I get warning `Cannot read property 'type' of undefined` from vscode
Error from console
```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.Literal (/Users/LLu/Code/Patient/client/node_modules/eslint/lib/rules/no-empty-character-class.js:49:26)
```

**Extra info**
I'm using eslint plugin with vscode

**eslint.rc**
```
{
  "parser": "typescript-eslint-parser",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
        "jsx": true
    }
  },
  "rules": {
    "no-empty-character-class":"error"
  }
} 
```

**Comment by soda0289** [comment] 2017-02-24 20:44
Hmm I'm having some difficulty reproducing the issue. Are you checking eslint with the command line tool installed globally or using a text editor or gulp task that would be installed locally?

**Comment by JamesHenry** [comment] 2017-02-24 20:45
@evollu The current version of VSCode will not use TypeScript 2.2.1 by default, have you configured it to use your local workspace version?

**Comment by evollu** [comment] 2017-02-24 20:52
both are throwing error but lets say it is just the command line
I just updated eslint to v3.16.1 and the error is gone.
but now it throws error on react plugin
```
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at EventEmitter.JSXOpeningElement (/Users/LLu/Code/Patient/client/node_modules/eslint-plugin-react/lib/rules/jsx-indent.js:230:32)
```
@JamesHenry I'm testing with command line with npm local packages. so the version should be correct and using ts 2.2.1

**Comment by soda0289** [comment] 2017-02-24 21:05
Thanks I can reproduce this error. It comes from the eslint source-code util. The function getNodeByRangeIndex() is failing to return a token. The function can be found here:
https://github.com/eslint/eslint/blob/v3.16.1/lib/util/source-code.js#L278-L300

This is most likely a problem with estraverse not entering the JSX node or invalid ranges in JSX nodes. More investigation will have to be done.

**Comment by soda0289** [comment] 2017-02-26 01:05
I had some free time to dig into this. The exception you posted had nothing to do with eslint like I originally thought. The react plugin depends on the token nodes to contain a start and end property, something that this parser did not produce. This caused the function getNodeByRangeIndex() to have an index of undefined which resulted in a null token being returned.

I also found some other bugs with JSX. The identifier property of a JsxAttribute node needed to be converted to JsxIdentifier type. Also self closing tags were did not have selfClosing property set correctly.

I have fixed all of the above issue. Just need some more tests but should have PR posted in a few hours.

**Comment by JamesHenry** [comment] 2017-02-26 17:48
Hmm this shouldn't have been closed by a single PR I don't think @soda0289?

**Comment by soda0289** [comment] 2017-02-26 17:51
@JamesHenry The issue mentioned above is caused by the missing start and end properties from the token nodes. But I found other JSX issues when testing the react plugin. I used the same issue number instead of opening a second one.

**Comment by JamesHenry** [comment] 2017-02-26 17:53
Cool, so the way to handle that in future is to use "refs" instead of "fixes".

http://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changes

**Comment by soda0289** [comment] 2017-02-26 17:54
@JamesHenry Sorry will be sure to use correct tags next time.

**Comment by JamesHenry** [comment] 2017-02-26 18:01
@soda0289, no worries!

**Closed** 2017-02-26 18:00 UTC
Labels: triage
