### ISSUE TITLE
declare global causing parse errors

### ISSUE THREAD

**Issue by milesj** [eslint/typescript-eslint-parser#570] opened 2018-11-28 05:28 UTC
**What version of TypeScript are you using?**

3.0

**What version of `typescript-eslint-parser` are you using?**

21.0.1

**What code were you trying to parse?**

```ts
declare global {
  namespace NodeJS {
    interface Process {
      beemo: {
        context: any;
        tool: BeemoTool;
      };
    }
  }
}
```

**What did you expect to happen?**

It parse.

**What happened?**

It fails with this error.

```
/Users/Miles/Sites/beemo/packages/core/src/index.ts
  17:15  error  Parse errors in imported module './types': Cannot read property '0' of undefined (undefined:undefined)  import/export
```

This has happened on 2 projects now, both because of `declare global`.

**Comment by milesj** [comment] 2018-11-28 05:34
Probably more related to `export *` coupled with `declare global`.

Here's the index file: https://github.com/milesj/beemo/blob/master/packages/core/src/index.ts#L17

And types file: https://github.com/milesj/beemo/blob/master/packages/core/src/types.ts#L62

**Comment by armano2** [comment] 2018-11-29 19:31
@milesj this issue is in https://github.com/benmosher/eslint-plugin-import 

this plugin is not supporting typescript https://github.com/benmosher/eslint-plugin-import/issues?q=is%3Aopen+is%3Aissue+label%3Atypescript

**Comment by milesj** [comment] 2018-11-29 20:03
This was working before a recent parser upgrade though. Do you know exactly what changed that may have caused this?

**Comment by armano2** [comment] 2018-11-29 20:54
@milesj hmm i did some testing and i set up config and all without your wrappers and its working fine

**Comment by milesj** [comment] 2018-11-29 21:02
This is the eslint config I'm using: https://github.com/milesj/build-tool-config/blob/master/packages/config/configs/eslint.js

Nothing atm stands out.

**Comment by armano2** [comment] 2018-11-29 21:22
yea i found it, and looks like its issue in AST after all xd

**Comment by armano2** [comment] 2018-11-29 21:46
```
TypeError: Cannot read property '0' of undefined
    at isGlobalAugmentation (******\typescript-eslint-parser\analyze-scope.js:32:26)
    at Referencer.TSModuleDeclaration (******\typescript-eslint-parser\analyze-scope.js:578:13)
    at Referencer.Visitor.visit (******\typescript-eslint-parser\node_modules\esrecurse\esrecurse.js:104:34)
    at Referencer.Visitor.visitChildren (******\typescript-eslint-parser\node_modules\esrecurse\esrecurse.js:83:38)
    at Referencer.Program (******\typescript-eslint-parser\node_modules\eslint-scope\lib\referencer.js:423:14)
    at Referencer.Visitor.visit (******\typescript-eslint-parser\node_modules\esrecurse\esrecurse.js:104:34)
    at module.exports (******\typescript-eslint-parser\analyze-scope.js:685:16)
    at Object.parseForESLint (******\typescript-eslint-parser\parser.js:74:26)
    at Object.exports.parse (******\typescript-eslint-parser\parser.js:79:17)
    at parse (******\test\node_modules\eslint-module-utils\parse.js:36:17)
```

**Comment by milesj** [comment] 2018-11-29 21:59
Oh nice! Luckily we found it.

**Comment by armano2** [comment] 2018-11-29 22:14
this is related to https://github.com/JamesHenry/typescript-estree/issues/27

**Comment by mysticatea** [comment] 2018-11-29 22:20
The cause seems that `eslint-plugin-import` doesn't give `tokens` option to the parser.

**Comment by mysticatea** [comment] 2018-11-29 22:36
ESLint gives some implicit options: https://github.com/eslint/eslint/blob/5d451c510c15abc41b5bb14b4955a7db96aeb100/lib/linter.js#L436

```js
  {
        loc: true,
        range: true,
        raw: true,
        tokens: true,
        comment: true,
        eslintVisitorKeys: true,
        eslintScopeManager: true,
        filePath
    }
```

`eslint-plugin-import` has some lacking implicit options: https://github.com/benmosher/eslint-plugin-import/blob/798eed7e559adab2eac07bf1b3e3518d4b7a4296/utils/parse.js#L9

```js
  // always include and attach comments
  parserOptions.comment = true
  parserOptions.attachComment = true

  // attach node locations
  parserOptions.loc = true

  // provide the `filePath` like eslint itself does, in `parserOptions`
  // https://github.com/eslint/eslint/blob/3ec436ee/lib/linter.js#L637
  parserOptions.filePath = path
```

This difference is the cause.

However, probably we should not assume those options.
We can have the required options in this parser itself.

**Comment by armano2** [comment] 2018-11-29 22:38
:>

**Comment by armano2** [comment] 2018-11-29 22:44
ok, i tested it, `options.tokens = true;` in [parser.js#L36](https://github.com/eslint/typescript-eslint-parser/blob/master/parser.js#L36), is solving issue

**Comment by armano2** [comment] 2018-11-29 22:51
ok, i tested it, `options.tokens = true;` in [parser.js#L35](https://github.com/eslint/typescript-eslint-parser/blob/master/parser.js#L35), is solving issue.

**Comment by armano2** [comment] 2018-11-29 22:57
@mysticatea why do check it there anyway?

we can could do
```js
if (node.declare && node.id && node.id.type === 'Identifier' && node.id.name === 'global') {
}
```

**Comment by mysticatea** [comment] 2018-11-29 22:58
See JamesHenry/typescript-estree#27

**Comment by armano2** [comment] 2018-11-29 23:11
@milesj for now you can patch it by adding `tokens: true,` to parserOptions: https://github.com/milesj/build-tool-config/blob/master/packages/config/configs/eslint.js#L31

**Comment by milesj** [comment] 2018-11-30 02:32
Thanks both for the deep debugging! Will give that patch a try.

**Comment by armano2** [comment] 2018-12-03 21:03
@platinumazure this issue got fixed in last release

**Comment by platinumazure** [comment] 2018-12-03 21:10
Thanks @armano2, next time you can ensure this happens yourself by including "fixes ####" in the commit summary, commit message, or PR body :smile:

Closing as this is resolved.

**Closed by platinumazure** 2018-12-03 21:10 UTC
Labels: bug
