### ISSUE TITLE
Class constructor overloads throws TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by unlight** [eslint/typescript-eslint-parser#222] opened 2017-04-18 07:32 UTC
**What version of TypeScript are you using?**
typescript@2.2.2

**What version of `typescript-eslint-parser` are you using?**
typescript-eslint-parser@2.1.0

**What code were you trying to parse?**

```
export class Book {

    constructor(fields: Partial<Book>);
  
    constructor(data: any = null) {
    }

}
```

**What did you expect to happen?**
No errors

**What happened?**
```
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at Referencer.visitFunction (d:\Dev\koa-boilerplate\node_modules\escope\lib\referencer.js:258:26)
    at Referencer.FunctionExpression (d:\Dev\koa-boilerplate\node_modules\escope\lib\referencer.js:569:18)
    at Referencer.Visitor.visit (d:\Dev\koa-boilerplate\node_modules\esrecurse\esrecurse.js:122:34)
    at Referencer.visitProperty (d:\Dev\koa-boilerplate\node_modules\escope\lib\referencer.js:297:18)
    at Referencer.MethodDefinition (d:\Dev\koa-boilerplate\node_modules\escope\lib\referencer.js:452:18)
    at Referencer.Visitor.visit (d:\Dev\koa-boilerplate\node_modules\esrecurse\esrecurse.js:122:34)
    at Referencer.Visitor.visitChildren (d:\Dev\koa-boilerplate\node_modules\esrecurse\esrecurse.js:101:38)
    at Referencer.Visitor.visit (d:\Dev\koa-boilerplate\node_modules\esrecurse\esrecurse.js:125:14)
    at Referencer.visitClass (d:\Dev\koa-boilerplate\node_modules\escope\lib\referencer.js:281:18)
    at Referencer.ClassDeclaration (d:\Dev\koa-boilerplate\node_modules\escope\lib\referencer.js:488:18)
```

**Comment by soda0289** [comment] 2017-04-18 13:07
This is a duplicate of this issue:
https://github.com/eslint/typescript-eslint-parser/issues/92

The problem was that escope did not know how to handle functions with empty bodies. We have since forked escope and will release it with eslint v4. There are still some rules that will crash when they see empty body functions but we are working to correct them.

**Closed by soda0289** 2017-04-18 13:07 UTC
Labels: bug, duplicate
