### ISSUE TITLE
Release build broken

### ISSUE THREAD

**Issue by nzakas** [eslint/typescript-eslint-parser#113] opened 2016-11-09 19:17 UTC
When I tried to do a release, it errors out. I think this has to do with the `.gitattributes` change, but I'm unfamiliar with how that works.

Relevant log snip:

```
Running tests
Calculating changes for release
Release is 1.0.0
Generating changelog
Committing to git

[master 52c116a] Build: package.json and changelog update for 1.0.0
 1 file changed, 9 insertions(+)

Generating 1.0.0
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "version" "1.0.0"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! Git working directory not clean.
npm ERR! M .travis.yml
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/lib/jenkins/workspace/Releases/typescript-eslint-parser Release/typescript-eslint-parser/npm-debug.log


npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "ci-release"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! typescript-eslint-parser@0.4.0 ci-release: `eslint-ci-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the typescript-eslint-parser@0.4.0 ci-release script 'eslint-ci-release'.
npm ERR! This is most likely a problem with the typescript-eslint-parser package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint-ci-release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs typescript-eslint-parser
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls typescript-eslint-parser
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/lib/jenkins/workspace/Releases/typescript-eslint-parser Release/typescript-eslint-parser/npm-debug.log
Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
Finished: FAILURE
```

[Full log](http://jenkins.eslint.org/job/Releases/job/typescript-eslint-parser%20Release/9/console)

@JamesHenry I think this problem is somehow related to https://github.com/eslint/typescript-eslint-parser/commit/45b987421a7f1835c5b1994292a7fda03aa8a030. Any ideas?

**Comment by JamesHenry** [comment] 2016-11-09 21:29
I don't know :/

The reason I submitted that was because I was having issues after the commit to add the `.gitattributes` file (https://github.com/eslint/typescript-eslint-parser/commit/68992eb0948c44889232e051d972876acfe3bbf4 )- IIRC I always had unstaged changes as my editor was altering the line endings.

I have never needed to use `.gitattributes` before so I am afraid I do not know exactly what the issue is.

**Comment by JamesHenry** [comment] 2016-11-09 22:03
I have submitted a PR (https://github.com/eslint/typescript-eslint-parser/pull/114) based on my interpretation of the information given here: https://schacon.github.io/git/gitattributes.html

> When text=auto normalization is enabled in an existing repository, any text files containing CRLFs should be normalized. If they are not they will be normalized the next time someone tries to change them, causing unfortunate misattribution

> If any files that should not be normalized show up in git status, unset their text attribute before running git add -u.

I did set the PR to close the issue, as it is impossible to verify the fix until a release job on jenkins is attempted.

**Comment by dannyfritz** [comment] 2016-11-10 02:08
#93 The original problem I was trying to solve when I originally added `.gitattributes` was that the test relied on character locations of everything, and Unix EOL uses `\n` whereas Windows uses `\r\n` which threw all the locations off and made all the tests fail on Windows. Using `.gitattributes` fixed it for me. If I am the only person with the problem, I am okay with having it as an unstaged change that works for me and just never commit it.

What it does is just tells git to always use certain line-endings. You can use a glob and tell git to always use `\n` on this file instead of the system's preferred `\r\n`.

**Closed** 2016-11-10 20:44 UTC
Labels: bug
