### ISSUE TITLE
This seems to fail when returning boolean literals

### ISSUE THREAD

**Issue by mitermayer** [eslint/typescript-eslint-parser#38] opened 2016-06-30 06:47 UTC
```typescript
function foo() : boolean {
   return true;
}
```

causes error: 

```
TypeError: Cannot read property 'match' of undefined
    at EventEmitter.Literal (./node_modules/eslint/lib/rules/no-octal-escape.js:36:37)
```

The problem is that node.raw is coming in as undefined

**Comment by mitermayer** [comment] 2016-06-30 07:20
Looks like the fix has been done on master but not on NPM

**Comment by mitermayer** [comment] 2016-06-30 07:20
```
1255             case SyntaxKind.TrueKeyword:
1256                 assign(result, {
1257                     type: "Literal",
1258                     value: true
1259                 });
1260                 break;
1261 
1262             case SyntaxKind.FalseKeyword:
1263                 assign(result, {
1264                     type: "Literal",
1265                     value: false
1266                 });
1267                 break;
1268 
```

**Comment by mitermayer** [comment] 2016-06-30 07:20
on NPM it is wrapped on quotes "false" and "true"

**Comment by mitermayer** [comment] 2016-06-30 07:21
for the values

**Comment by nzakas** [comment] 2016-06-30 16:08
Duplicate of https://github.com/eslint/typescript-eslint-parser/issues/21

**Closed by nzakas** 2016-06-30 16:08 UTC
Labels: triage
