### ISSUE TITLE
false is not parsed as expected

### ISSUE THREAD

**Issue by ranzwix** [eslint/typescript-eslint-parser#21] opened 2016-03-06 08:56 UTC
**typescript-eslint-parser version**: 0.1.0-alpha-1

Hi, 

When I parse the string "false" (inside a js file), I get the AST
[typescript-eslint-parser-result.txt](https://github.com/eslint/typescript-eslint-parser/files/160244/typescript-eslint-parser-result.txt)

**Where the actual AST should be : **

[eslint-parser-result.txt](https://github.com/eslint/typescript-eslint-parser/files/160245/eslint-parser-result.txt)

In addition, I noticed that creating boolean literals is missing the "raw" field value, which will make it fail in eslint.

Best regards,
Ran

**Comment by nzakas** [comment] 2016-03-06 16:22
Duplicate of #1. Already fixed on master.

**Closed by nzakas** 2016-03-06 16:22 UTC
Labels: triage

**Comment by mitermayer** [comment] 2016-06-30 23:01
@nzakas when are you going to do a release to fix this ?
