### ISSUE TITLE
Error while checking incomplete code

### ISSUE THREAD

**Issue by jskorepa** [eslint/typescript-eslint-parser#349] opened 2017-08-12 10:58 UTC
**What version of TypeScript are you using?**
2.4.2

**What version of `typescript-eslint-parser` are you using?**
5.0.1

**What code were you trying to parse?**

```
export class Klass {
  method2()
}
```

**What did you expect to happen?**
To report problem, but not throw unhandled Error

**What happened?**
```
$ ./node_modules/.bin/eslint --parser typescript-eslint-parser source.ts
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at Linter.onCodePathStart (/home/jakub.skorepa/Dokumenty/html/workstream_node/backend/node_modules/eslint/lib/rules/array-callback-return.js:193:34)
    at emitTwo (events.js:130:20)
    at Linter.emit (events.js:213:7)
    at processCodePathToEnter (/home/jakub.skorepa/Dokumenty/html/workstream_node/backend/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:357:30)
    at CodePathAnalyzer.enterNode (/home/jakub.skorepa/Dokumenty/html/workstream_node/backend/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:599:9)
    at Traverser.enter (/home/jakub.skorepa/Dokumenty/html/workstream_node/backend/node_modules/eslint/lib/linter.js:925:36)
    at Traverser.__execute (/home/jakub.skorepa/Dokumenty/html/workstream_node/backend/node_modules/estraverse/estraverse.js:397:31)
    at Traverser.traverse (/home/jakub.skorepa/Dokumenty/html/workstream_node/backend/node_modules/estraverse/estraverse.js:501:28)
    at Traverser.traverse (/home/jakub.skorepa/Dokumenty/html/workstream_node/backend/node_modules/eslint/lib/util/traverser.js:31:22)
```

It is really annoying if check-as-you-type is enabled in atom.
![image](https://user-images.githubusercontent.com/21140749/29240055-bf382964-7f5d-11e7-9c24-73bd70a3aaf6.png)

**Comment by JamesHenry** [comment] 2017-10-22 15:17
Thanks so much for your patience on this, @jskorepa!

I am not an Atom user myself, are you saying this behaviour is different to standard ESLint usage? i.e. when it is using a parser other than `typescript-eslint-parser`

Would you mind also checking if the behaviour is still reproducible using the latest version of this parser and the supported stable TypeScript version (currently 2.5.3)

**Comment by j-f1** [comment] 2017-10-22 15:29
> are you saying this behaviour is different to standard ESLint usage

Typically, `linter-eslint` will tell you that there’s a syntax error in your code, without throwing an error:

<img width="288" alt="screen shot 2017-10-22 at 11 21 20" src="https://user-images.githubusercontent.com/25517624/31863402-4e20e6ee-b71b-11e7-9c29-8ee164169a9b.png">

I’m able to reproduce this with the `atom-ide-ui` and `linter-eslint`:

<img width="512" alt="screen shot 2017-10-22 at 11 26 22" src="https://user-images.githubusercontent.com/25517624/31863477-ea733fa6-b71b-11e7-84c9-25580267ac02.png">

The error stack looks to be similar to the one provided above. The culprit appears to be that `method2()` is interpreted as an overload, making this a duplicate of #389.

**Comment by JamesHenry** [comment] 2017-10-22 15:49
Ah, brilliant thanks @j-f1! That indeed confirms this is actually a duplicate of #389, it's just manifesting in a different context.

I will close this one in order to focus all attention in one place.

Thanks again @jskorepa, please follow along with the progress of #389.

**Closed by JamesHenry** 2017-10-22 15:49 UTC
Labels: response required
