### ISSUE TITLE
no-restricted-globals: false positive on class property

### ISSUE THREAD

**Issue by burnnat** [eslint/typescript-eslint-parser#487] opened 2018-06-12 19:56 UTC
**What version of TypeScript are you using?**
2.9.1

**What version of `typescript-eslint-parser` are you using?**
16.0.0

**What code were you trying to parse?**
With `no-restricted-globals` rule enabled (`"no-restricted-globals": [2, "status"]`):
```ts
export default class Test {
	private status: string;

	getStatus() {
		return this.status;
	}
}
```

**What did you expect to happen?**
Lint completes without error.

**What happened?**
False positive for `no-restricted-globals`:

    2:10  error  Unexpected use of 'status'  no-restricted-globals

**Comment by burnnat** [comment] 2018-06-13 15:17
It appears this is also an issue with interface properties:
```ts
interface Test {
    status: string;
}
```

**Comment by christophehurpeau** [comment] 2018-06-28 21:17
seems to be a duplicate of #414

**Closed** 2018-11-13 04:38 UTC
Labels: ESLint rule/integration issue
